"""Phase-0 analysis: facade (C1) + Go/No-Go routing (S11)."""

from .facade import (
    AxisFacadeResult,
    FacadeSpec,
    FacadeTable,
    analyze_axis_facade,
    analyze_facade,
)
from .routing import (
    MAIN_LINE,
    PLAN_B,
    PLAN_D,
    RoutingDecision,
    RoutingInputs,
    RoutingThresholds,
    decide_route,
)
from .ood import (
    C1NullRelativeEffect,
    C1SensitivityPoint,
    C1SensitivitySummary,
    HMArmVerdict,
    HMCellResult,
    HM_CI_LEVEL,
    HM_REQUIRED_PASS_CELLS,
    HM_SPEARMAN_THRESHOLD,
    HM_TOTAL_CELLS,
    OODDistribution,
    OODItemStats,
    SpearmanBootstrap,
    activation_norm_inflation,
    bootstrap_spearman,
    c1_null_relative_effect,
    estimate_ood_distribution,
    hm_arm_verdict,
    hm_cell_result,
    per_item_ood_stats,
    summarize_c1_layer_norm_sensitivity,
    whitened_mahalanobis,
)

__all__ = [
    "AxisFacadeResult",
    "FacadeSpec",
    "FacadeTable",
    "analyze_axis_facade",
    "analyze_facade",
    "MAIN_LINE",
    "PLAN_B",
    "PLAN_D",
    "RoutingDecision",
    "RoutingInputs",
    "RoutingThresholds",
    "decide_route",
    "OODDistribution",
    "OODItemStats",
    "SpearmanBootstrap",
    "HMCellResult",
    "HMArmVerdict",
    "HM_SPEARMAN_THRESHOLD",
    "HM_CI_LEVEL",
    "HM_REQUIRED_PASS_CELLS",
    "HM_TOTAL_CELLS",
    "estimate_ood_distribution",
    "whitened_mahalanobis",
    "activation_norm_inflation",
    "per_item_ood_stats",
    "bootstrap_spearman",
    "hm_cell_result",
    "hm_arm_verdict",
    "C1NullRelativeEffect",
    "c1_null_relative_effect",
    "C1SensitivityPoint",
    "C1SensitivitySummary",
    "summarize_c1_layer_norm_sensitivity",
]
