"""Generate the evidence-scoped failure-taxonomy table."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "docs" / "paper" / "tables" / "failure-taxonomy.tex"

ROWS = [
    (
        "F1. Legible-but-non-transfer facade",
        "Axis is representationally legible, but steering does not beat best-prompt behavior",
        "Supported in tested scope by the facade measurement and frozen behavioral adjudication",
        "For the tested model/method/axis, show diagnostic status but withhold a validated-control state",
    ),
    (
        "F2. Calibration backfire in the steer-vs-prompt contrast",
        "Uncertainty/calibration axis is worse for steer than for the bounded prompt (steer-vs-prompt contrast; direct steer-vs-baseline $\\approx 0$)",
        "Supported/generalized in the tested 2$\\times$2; mechanism remains open after the pre-registered null",
        "For the tested cells, present a comparator-bound warning instead of a validated calibration control",
    ),
    (
        "F3. Coherence-fragility corridor",
        "Higher steering strength risks coherence collapse or forces conservative usable $\\alpha$",
        "Instrumented by preregistered coherence gates; not triggered in tested cells",
        "Withhold the tested control state if coherence deteriorates before meaningful gain",
    ),
    (
        "F4. Layer-sensitive instability",
        "Axis effect depends strongly on layer choice",
        "Supported in scope by layer sensitivity and per-model layer re-derivation",
        "Keep the evidence tier layer-specific until stability is demonstrated in the intended setting",
    ),
    (
        "F5. Axis extraction degeneration",
        "Extracted direction overshoots or fails to encode intended construct",
        "Supported in scope by the focus-axis overshoot/no-facade result",
        "Exclude the tested axis from validated-control claims until its extraction is redesigned and re-evaluated",
    ),
]


def render() -> str:
    lines = [
        "% Generated by docs/paper/scripts/make_failure_taxonomy.py; do not edit by hand.",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\caption{Operational failure taxonomy from the proposed evidence-accounting framework. This evidence-tagged definition table maps tested model evidence to conditional interface states; it is not a deployment study or result table.}",
        "  \\label{tab:failure-taxonomy}",
        "  \\scriptsize",
        "  \\begin{tabular}{L{0.15\\linewidth}L{0.25\\linewidth}L{0.22\\linewidth}L{0.28\\linewidth}}",
        "    \\toprule",
        "    Class & Observable symptom & Evidence status & Conditional interface decision \\\\",
        "    \\midrule",
    ]
    lines.extend(f"    {a} & {b} & {c} & {d} \\\\" for a, b, c, d in ROWS)
    lines.extend(["    \\bottomrule", "  \\end{tabular}", "\\end{table*}", ""])
    return "\n".join(lines)


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
