"""Generate the C2 4-cell delta LaTeX table from frozen JSON artifacts."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ARM_DIR = ROOT / "results" / "arm_full"
SUMMARY = ARM_DIR / "arm_matrix_summary.json"
E0005 = ROOT / "results" / "c2b_adjudication_hf_2026-07-24" / "c2b_adjudication_results.json"
OUT = ROOT / "docs" / "paper" / "tables" / "c2-delta-4cell.tex"

METHOD_LABEL = {"caa": "CAA", "iti": "ITI"}
MODEL_LABEL = {"qwen2.5-7b": "Qwen2.5-7B", "llama3-8b": "Llama-3-8B"}
AXIS_LABEL = {"deliberation": "Deliberation", "skepticism": "Skepticism", "uncertainty_awareness": "Uncertainty"}


def tex_escape(value: object) -> str:
    text = str(value)
    return (text.replace("\\", r"\textbackslash{}")
                .replace("&", r"\&")
                .replace("%", r"\%")
                .replace("_", r"\_")
                .replace("#", r"\#"))


def fmt_num(x: float) -> str:
    if abs(x) < 0.0005:
        x = 0.0
    return f"{x:+.3f}"


def main() -> None:
    summary = json.loads(SUMMARY.read_text(encoding="utf-8"))
    e0005 = json.loads(E0005.read_text(encoding="utf-8"))
    ci_level = e0005["frozen_params"]["bonferroni_ci_level"]
    delta = e0005["frozen_params"]["delta"]
    rows = []
    for cell in summary["cells"]:
        result_path = ARM_DIR / f"cell_{cell['cell_key']}" / "c2b_adjudication_results.json"
        result = json.loads(result_path.read_text(encoding="utf-8"))
        for axis in result["axes"]:
            rows.append({
                "method": METHOD_LABEL.get(cell["method"], cell["method"].upper()),
                "model": MODEL_LABEL.get(cell["model_label"], cell["model_label"]),
                "axis": AXIS_LABEL.get(axis["axis"], axis["axis"]),
                "n_dev": axis["n_dev"],
                "n_test": axis["n_test"],
                "alpha": axis["dev_selection"]["frozen_alpha"],
                "prompt": axis["dev_selection"]["best_prompt_id"],
                "mean": axis["mean_diff"],
                "lo": axis["ci_lo"],
                "hi": axis["ci_hi"],
                "coherence": axis["coherence_ok"],
                "passed": axis["passed"],
                "verdict": result["verdict"],
            })

    lines = []
    lines.append(r"% Auto-generated by docs/paper/scripts/make_c2_delta_table.py from frozen JSON artifacts.")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"  \centering")
    lines.append(r"  \caption{Frozen prompt-vs-latent behavioral adjudication across CAA/ITI $\times$ Qwen/Llama. The table supports Claim C2 and is generated from frozen robustness-arm artifacts; CAA$\times$Qwen reproduces the original Qwen adjudication. $\Delta$ is TEST paired steer--prompt outcome; intervals are Bonferroni two-sided CIs at level " + f"{ci_level:.5f}" + r"; the pre-registered meaningful margin is $\delta=" + f"{delta:.2f}" + r"$.}")
    lines.append(r"  \label{tab:c2-delta-4cell}")
    lines.append(r"  \scriptsize")
    lines.append(r"  \begin{tabular}{lllrrrll}")
    lines.append(r"    \toprule")
    lines.append(r"    Method & Model & Axis & $N_{dev}$ & $N_{test}$ & $\alpha$ & $\Delta$ [CI] & Gate / pass \\")
    lines.append(r"    \midrule")
    last_cell = None
    for r in rows:
        cell = (r["method"], r["model"])
        if last_cell is not None and cell != last_cell:
            lines.append(r"    \addlinespace")
        last_cell = cell
        gate = "ok" if r["coherence"] else "fail"
        passed = "PASS" if r["passed"] else "fail"
        ci = f"{fmt_num(r['mean'])} [{fmt_num(r['lo'])}, {fmt_num(r['hi'])}]"
        lines.append(
            "    "
            + " & ".join([
                tex_escape(r["method"]), tex_escape(r["model"]), tex_escape(r["axis"]),
                str(r["n_dev"]), str(r["n_test"]), f"{r['alpha']:g}",
                tex_escape(ci), tex_escape(f"{gate} / {passed}"),
            ])
            + r" \\")
    lines.append(r"    \bottomrule")
    lines.append(r"  \end{tabular}")
    lines.append(r"  \par\smallskip\raggedright\scriptsize\emph{Notes.} Pass/fail is computed from the unrounded frozen JSON. Displayed means and intervals are rounded to three decimals; a fail can therefore have a small positive displayed estimate or boundary. A pass requires an unrounded CI excluding 0, mean $\ge \delta=0.05$, and the coherence gate to pass, so ITI$\times$Qwen deliberation remains fail because its mean is below $\delta$. The DEV-selected best prompt for each axis/model is identified by its artifact-registry ID; full prompt text is provided in the supplementary manifest (\texttt{c2-delta-4cell.yaml}).")
    lines.append(r"\end{table*}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
