"""Generate the C1 two-model comparison table from committed JSON artifacts."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCES = [
    {
        "label": "Qwen2.5-7B",
        "experiment_id": "c1-facade-d710b4b4-0001",
        "path": ROOT / "results" / "gpu_7b_2026-07-23" / "c1" / "c1_facade_results.json",
    },
    {
        "label": "Llama-3-8B",
        "experiment_id": "c1-facade-1dcc4fa7-0001",
        "path": ROOT / "results" / "llama_c1_facade_2026-07-24" / "c1_facade_results.json",
    },
]
OUT = ROOT / "docs" / "paper" / "tables" / "c1-twomodel.tex"

AXIS_LABEL = {
    "deliberation": "Deliberation",
    "skepticism": "Skepticism",
    "uncertainty_awareness": "Uncertainty",
    "focus": "Focus",
}


def fmt_num(x: float) -> str:
    if abs(x) < 0.0005:
        x = 0.0
    return f"{x:.3f}"


def tex_escape(value: object) -> str:
    text = str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
    )


def main() -> None:
    rows = []
    for source in SOURCES:
        data = json.loads(source["path"].read_text(encoding="utf-8"))
        for axis in data["axes"]:
            rows.append(
                {
                    "model": source["label"],
                    "experiment_id": source["experiment_id"],
                    "axis": AXIS_LABEL.get(axis["axis"], axis["axis"]),
                    "ratio": axis["facade_ratio"],
                    "lo": axis["facade_ratio_ci_lo"],
                    "hi": axis["facade_ratio_ci_hi"],
                    "holds": bool(axis["facade_gap_holds_ci"]),
                }
            )

    lines = [
        r"% Auto-generated by docs/paper/scripts/make_c1_twomodel_table.py from committed C1 JSON artifacts.",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Exploratory C1 two-model comparison. Ratios and confidence intervals are generated from the committed Qwen and Llama C1 JSON artifacts, not hand-entered. C1 has two-model support at the aggregate level, but the per-axis composition differs across models.}",
        r"  \label{tab:c1-twomodel}",
        r"  \scriptsize",
        r"  \begin{tabular}{lllc}",
        r"    \toprule",
        r"    Model & Axis & Facade ratio [95\% CI] & Facade? \\",
        r"    \midrule",
    ]
    last_model = None
    for row in rows:
        if last_model is not None and row["model"] != last_model:
            lines.append(r"    \addlinespace")
        last_model = row["model"]
        ratio_ci = f"{fmt_num(row['ratio'])} [{fmt_num(row['lo'])}, {fmt_num(row['hi'])}]"
        verdict = "yes" if row["holds"] else "no"
        lines.append(
            "    "
            + " & ".join(
                [
                    tex_escape(row["model"]),
                    tex_escape(row["axis"]),
                    tex_escape(ratio_ci),
                    tex_escape(verdict),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
